import '../models/exercise_model.dart';

class ExerciseData {
  ExerciseData._();

  static const List<Map<String, dynamic>> warmup = [
    {'name': 'Pallof Press', 'reps': '10/side', 'hasWeight': true, 'note': 'ثبّت جسمك وحرك ذراعك فقط'},
    {'name': 'Pallof Rotation', 'reps': '10/side', 'hasWeight': true, 'note': 'حوضك ثابت'},
    {'name': 'External Rotation', 'reps': '10 reps', 'hasWeight': true, 'note': 'من الكتف فقط'},
    {'name': 'Scapula Push Plus', 'reps': '10 reps', 'hasWeight': true, 'note': 'من لوح الكتف — وزن خفيف'},
    {'name': 'Neck Extension', 'reps': '12 reps', 'hasWeight': true, 'note': 'وزن خفيف جداً — أسفل الرأس'},
    {'name': 'Neck Flexion', 'reps': '12 reps', 'hasWeight': true, 'note': 'وزن خفيف — الذقن للصدر'},
  ];

  static const Map<String, List<Map<String, dynamic>>> sessions = {
    'Upper A': [
      {'name': 'Smith High Incline Press', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB High Incline Press', 'alt2': '', 'note': 'ضم ايدك لجوه عشان تحاكي اتجاه الياف الصدر العالي'},
      {'name': 'Machine Wide Grip Lat Pulldown', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable Wide Grip Lat', 'alt2': '', 'note': 'ركز في مسار كوعك'},
      {'name': 'Chest Press Machine', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~10', 'rest': '3~5', 'muscle': 'صدر مستوي', 'alt1': 'DB Flat Press', 'alt2': '', 'note': ''},
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': 'Cable Row', 'note': 'افتح كيعانك لبره حاول تقرب من زاوية 90'},
      {'name': 'SA Tricep Pushdown', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'Double Rope Pushdown', 'alt2': '', 'note': ''},
      {'name': 'DB Preacher Curl', 'primary': true, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'Face Away Curl', 'alt2': 'DB Curls', 'note': 'بلاش مدى حركي زياده من الكتف'},
      {'name': 'Reverse Grip Curls', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ساعد أمامي', 'alt1': 'DB Reverse Curl', 'alt2': 'Barbell Reverse Curl', 'note': ''},
    ],
    'Lower A': [
      {'name': 'Machine Lateral Raises', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'Cable Lateral Raises', 'alt2': 'DB Lateral Raises', 'note': 'الحركه تبقي طالعه من كتفك لوحده'},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
      {'name': 'Hack Squat', 'primary': true, 'wu': '1~3', 'sets': 1, 'reps': '5~8', 'rest': '3~5', 'muscle': 'رجل كوادز', 'alt1': 'Smith Squat', 'alt2': 'Leg Press', 'note': '120 درجه من ثني الركبه يكفي لاستهداف الكوادز'},
      {'name': 'SA Rear Delt Flies', 'primary': false, 'wu': '0', 'sets': 1, 'reps': '6~10', 'rest': '2~3', 'muscle': 'كتف خلفي', 'alt1': 'Reverse Pec Dec', 'alt2': '', 'note': ''},
      {'name': 'Seated Leg Curl', 'primary': true, 'wu': '1~2', 'sets': 1, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل خلفيه', 'alt1': 'Lying Leg Curl', 'alt2': '', 'note': ''},
      {'name': 'Leg Extension', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل أماميه', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'Hip Adduction', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ضمه', 'alt1': 'Cable Hip Adduction', 'alt2': '', 'note': ''},
      {'name': 'Wrist Curls', 'primary': false, 'wu': '0', 'sets': 3, 'reps': '6~10', 'rest': '1~2', 'muscle': 'ساعد خلفي', 'alt1': '', 'alt2': '', 'note': ''},
    ],
    'Upper B': [
      {'name': 'Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'صدر مستوي', 'alt1': 'DB Flat Press', 'alt2': 'Smith Flat Press', 'note': ''},
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': 'Cable Row', 'note': ''},
      {'name': 'Incline Chest Press Machine', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '6~10', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB Incline Press', 'alt2': 'Smith Incline Press', 'note': ''},
      {'name': 'SA Lat Row', 'primary': false, 'wu': '0', 'sets': 1, 'reps': '6~10', 'rest': '2~3', 'muscle': 'لاتس', 'alt1': 'Cable SA Lat Row', 'alt2': 'DB SA Lat Row', 'note': ''},
      {'name': 'Face Away Curl', 'primary': true, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'DB Preacher Curl', 'alt2': 'DB Curls', 'note': ''},
      {'name': 'Overhead Extension', 'primary': true, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'DB Skull Crusher', 'alt2': '', 'note': ''},
      {'name': 'Cable Shrugs', 'primary': false, 'wu': '1', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ترابيس', 'alt1': 'Smith Kelso Shrugs', 'alt2': 'DB Kelso Shrugs', 'note': ''},
    ],
    'Lower B': [
      {'name': 'Cable Lateral Raises', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'DB Lateral Raises', 'alt2': '', 'note': ''},
      {'name': 'SLDL', 'primary': true, 'wu': '1~3', 'sets': 1, 'reps': '5~7', 'rest': '3~5', 'muscle': 'جلوتس', 'alt1': 'RDL', 'alt2': 'Hip Extension', 'note': ''},
      {'name': 'Seated Leg Curl', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل خلفيه', 'alt1': 'Lying Leg Curl', 'alt2': '', 'note': ''},
      {'name': 'Leg Extension', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل أماميه', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'Hip Adduction', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ضمه', 'alt1': 'Cable Hip Adduction', 'alt2': '', 'note': ''},
      {'name': 'Lat Pulldown Crunches', 'primary': false, 'wu': '0', 'sets': 1, 'reps': '6~10', 'rest': '1~2', 'muscle': 'بطن', 'alt1': 'Cable Crunch', 'alt2': '', 'note': ''},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
    ],
    'Anterior A': [
      {'name': 'Machine Shoulder Press', 'primary': true, 'wu': '1~2', 'sets': 1, 'reps': '6~8', 'rest': '3~5', 'muscle': 'كتف أمامي', 'alt1': 'DB Shoulder Press', 'alt2': 'Smith Shoulder Press', 'note': ''},
      {'name': 'Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 3, 'reps': '6~10', 'rest': '3~5', 'muscle': 'صدر مستوي', 'alt1': 'DB Flat Press', 'alt2': 'Smith Flat Press', 'note': ''},
      {'name': 'Hack Squat', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '5~8', 'rest': '3~5', 'muscle': 'رجل كوادز', 'alt1': 'Smith Squat', 'alt2': 'Leg Press', 'note': ''},
      {'name': 'Machine Lateral Raises', 'primary': true, 'wu': '1~2', 'sets': 3, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'Cable Lateral Raises', 'alt2': 'DB Lateral Raises', 'note': ''},
      {'name': 'Overhead Extension', 'primary': true, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'DB Skull Crusher', 'alt2': '', 'note': ''},
      {'name': 'Butterfly', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '6~10', 'rest': '2~3', 'muscle': 'صدر مستوي', 'alt1': 'Cable Fly', 'alt2': 'DB Fly', 'note': ''},
      {'name': 'Lat Pulldown Crunches', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '1~2', 'muscle': 'بطن', 'alt1': 'Cable Crunch', 'alt2': '', 'note': ''},
      {'name': 'Leg Extension', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل أماميه', 'alt1': '', 'alt2': '', 'note': ''},
    ],
    'Posterior A': [
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': 'Cable Row', 'note': ''},
      {'name': 'Machine Wide Grip Lat Pulldown', 'primary': true, 'wu': '1~3', 'sets': 3, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable Wide Grip Lat', 'alt2': '', 'note': ''},
      {'name': 'RDL', 'primary': true, 'wu': '1~3', 'sets': 1, 'reps': '5~8', 'rest': '3~5', 'muscle': 'جلوتس', 'alt1': 'Hip Extension', 'alt2': 'Hip Thrust', 'note': ''},
      {'name': 'SA Rear Delt Flies', 'primary': false, 'wu': '0', 'sets': 1, 'reps': '6~10', 'rest': '2~3', 'muscle': 'كتف خلفي', 'alt1': 'Reverse Pec Dec', 'alt2': '', 'note': ''},
      {'name': 'Seated Leg Curl', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل خلفيه', 'alt1': 'Lying Leg Curl', 'alt2': '', 'note': ''},
      {'name': 'Preacher Curl Machine', 'primary': true, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'Face In Curls', 'alt2': '', 'note': ''},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '5~7', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
      {'name': 'Wrist Curls', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '1~2', 'muscle': 'ساعد خلفي', 'alt1': 'Reverse Curl', 'alt2': '', 'note': ''},
    ],
    'Anterior B': [
      {'name': 'Incline Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~10', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB Incline Press', 'alt2': 'Smith Incline Press', 'note': ''},
      {'name': 'Machine Shoulder Press', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'كتف أمامي', 'alt1': 'DB Shoulder Press', 'alt2': 'Smith Shoulder Press', 'note': ''},
      {'name': 'Leg Extension', 'primary': true, 'wu': '1~2', 'sets': 3, 'reps': '8~12', 'rest': '3~5', 'muscle': 'رجل أماميه', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'Cable Lateral Raises', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'DB Lateral Raises', 'alt2': '', 'note': ''},
      {'name': 'SA Tricep Pushdown', 'primary': true, 'wu': '0', 'sets': 3, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'Double Rope Pushdown', 'alt2': '', 'note': ''},
      {'name': 'Butterfly', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '6~10', 'rest': '2~3', 'muscle': 'صدر مستوي', 'alt1': 'Cable Fly', 'alt2': '', 'note': ''},
      {'name': 'Hip Adduction', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ضمه', 'alt1': 'Cable Hip Adduction', 'alt2': '', 'note': ''},
      {'name': 'Reverse Grip Curls', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ساعد أمامي', 'alt1': 'DB Reverse Curl', 'alt2': 'Barbell Reverse Curl', 'note': ''},
    ],
    'Posterior B': [
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': 'Cable Row', 'note': ''},
      {'name': 'Machine Wide Grip Lat Pulldown', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable Wide Grip Lat', 'alt2': '', 'note': ''},
      {'name': 'SLDL', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'جلوتس', 'alt1': 'RDL', 'alt2': '', 'note': ''},
      {'name': 'Seated Leg Curl', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل خلفيه', 'alt1': 'Lying Leg Curl', 'alt2': '', 'note': ''},
      {'name': 'SA Rear Delt Flies', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'كتف خلفي', 'alt1': 'Reverse Pec Dec', 'alt2': '', 'note': ''},
      {'name': 'Preacher Curl Machine', 'primary': true, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'Face In Curls', 'alt2': '', 'note': ''},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '5~7', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
    ],
    'Full Body #1': [
      {'name': 'Hack Squat', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'رجل كوادز', 'alt1': 'Smith Squat', 'alt2': 'Leg Press', 'note': ''},
      {'name': 'Machine Wide Grip Lat Pulldown', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable Wide Grip Lat', 'alt2': '', 'note': ''},
      {'name': 'Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~10', 'rest': '3~5', 'muscle': 'صدر مستوي', 'alt1': 'DB Flat Press', 'alt2': '', 'note': ''},
      {'name': 'Machine Lateral Raises', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'DB Lateral Raises', 'alt2': '', 'note': ''},
      {'name': 'DB Preacher Curl', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'Face Away Curl', 'alt2': '', 'note': ''},
      {'name': 'SA Tricep Pushdown', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'Overhead Extension', 'alt2': '', 'note': ''},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '5~7', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
    ],
    'Full Body #2': [
      {'name': 'SLDL', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'جلوتس', 'alt1': 'RDL', 'alt2': '', 'note': ''},
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': '', 'note': ''},
      {'name': 'Incline Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB Incline Press', 'alt2': '', 'note': ''},
      {'name': 'Seated Leg Curl', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل خلفيه', 'alt1': 'Lying Leg Curl', 'alt2': '', 'note': ''},
      {'name': 'Cable Lateral Raises', 'primary': false, 'wu': '1', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'DB Lateral Raises', 'alt2': '', 'note': ''},
      {'name': 'Face Away Curl', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'DB Curls', 'alt2': '', 'note': ''},
      {'name': 'Overhead Extension', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'DB Skull Crusher', 'alt2': '', 'note': ''},
    ],
    'Full Body #3': [
      {'name': 'Leg Extension', 'primary': true, 'wu': '1~2', 'sets': 3, 'reps': '8~12', 'rest': '3~5', 'muscle': 'رجل أماميه', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'Machine Wide Grip Lat Pulldown', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable Wide Grip Lat', 'alt2': '', 'note': ''},
      {'name': 'Machine Shoulder Press', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'كتف أمامي', 'alt1': 'DB Shoulder Press', 'alt2': '', 'note': ''},
      {'name': 'Incline Chest Press Machine', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB Incline Press', 'alt2': 'Smith Incline Press', 'note': ''},
      {'name': 'SA Y Raises', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'Machine Lateral Raises', 'alt2': 'DB Lateral Raises', 'note': ''},
      {'name': 'Face Away Curl', 'primary': true, 'wu': '0', 'sets': 1, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'DB Preacher Curl', 'alt2': 'DB Curls', 'note': ''},
      {'name': 'Overhead Extension', 'primary': true, 'wu': '0', 'sets': 1, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'DB Skull Crusher', 'alt2': '', 'note': ''},
      {'name': 'Hip Adduction', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ضمه', 'alt1': 'Cable Hip Adduction', 'alt2': '', 'note': ''},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
    ],
    'Chest & Back': [
      {'name': 'Incline Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '4~6', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB Incline Press', 'alt2': 'Smith Incline Press', 'note': ''},
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': 'Cable Row', 'note': ''},
      {'name': 'DB Flat Press', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~10', 'rest': '3~5', 'muscle': 'صدر مستوي', 'alt1': 'Smith Flat Press', 'alt2': '', 'note': ''},
      {'name': 'Cable Wide Grip Lat Pulldown', 'primary': true, 'wu': '1~2', 'sets': 1, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Machine Wide Grip Lat', 'alt2': '', 'note': ''},
      {'name': 'SA Lat Row', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '5~7', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable SA Lat Row', 'alt2': '', 'note': ''},
      {'name': 'Cable Shrugs', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترابيس', 'alt1': 'DB Shrugs', 'alt2': '', 'note': ''},
      {'name': 'SA Rear Delt Flies', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'كتف خلفي', 'alt1': 'Reverse Pec Dec', 'alt2': '', 'note': ''},
    ],
    'Shoulders & Arms': [
      {'name': 'Machine Lateral Raises', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'DB Lateral Raises', 'alt2': '', 'note': ''},
      {'name': 'SA Tricep Pushdown', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'Double Rope Pushdown', 'alt2': '', 'note': ''},
      {'name': 'Machine Shoulder Press', 'primary': true, 'wu': '1~3', 'sets': 1, 'reps': '5~8', 'rest': '3~5', 'muscle': 'كتف أمامي', 'alt1': 'DB Shoulder Press', 'alt2': '', 'note': ''},
      {'name': 'DB Preacher Curl', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'Face Away Curl', 'alt2': 'DB Curls', 'note': ''},
      {'name': 'Reverse Grip Curls', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ساعد أمامي', 'alt1': 'DB Reverse Curl', 'alt2': 'Barbell Reverse Curl', 'note': ''},
      {'name': 'Overhead Extension', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'DB Skull Crusher', 'alt2': '', 'note': ''},
      {'name': 'Wrist Curls', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '1~2', 'muscle': 'ساعد خلفي', 'alt1': '', 'alt2': '', 'note': ''},
    ],
    'Lower A (Arnold)': [
      {'name': 'Seated Leg Curl', 'primary': true, 'wu': '1~2', 'sets': 3, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل خلفيه', 'alt1': 'Lying Leg Curl', 'alt2': '', 'note': ''},
      {'name': 'Hip Adduction', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ضمه', 'alt1': 'Cable Hip Adduction', 'alt2': '', 'note': ''},
      {'name': 'Hip Extension', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'جلوتس', 'alt1': 'Lying Leg Curl', 'alt2': '', 'note': ''},
      {'name': 'Leg Extension', 'primary': true, 'wu': '1~2', 'sets': 3, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل أماميه', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '1~2', 'sets': 3, 'reps': '5~7', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
      {'name': 'Lat Pulldown Crunches', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '1~2', 'muscle': 'بطن', 'alt1': 'Cable Crunch', 'alt2': '', 'note': ''},
    ],
    'Upper (Arnold)': [
      {'name': 'Cable Wide Grip Lat Pulldown', 'primary': true, 'wu': '1~2', 'sets': 1, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Machine Wide Grip Lat', 'alt2': '', 'note': ''},
      {'name': 'SA Lat Row', 'primary': false, 'wu': '1~2', 'sets': 1, 'reps': '5~7', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable SA Lat Row', 'alt2': '', 'note': ''},
      {'name': 'Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'صدر مستوي', 'alt1': 'DB Flat Press', 'alt2': 'Smith Flat Press', 'note': ''},
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': 'Cable Row', 'note': ''},
      {'name': 'Incline Chest Press Machine', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~10', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB Incline Press', 'alt2': 'Smith Incline Press', 'note': ''},
      {'name': 'Face Away Curl', 'primary': true, 'wu': '0', 'sets': 3, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'DB Preacher Curl', 'alt2': 'DB Curls', 'note': ''},
      {'name': 'SA Tricep Pushdown', 'primary': true, 'wu': '1~2', 'sets': 3, 'reps': '5~7', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'Double Rope Pushdown', 'alt2': '', 'note': ''},
    ],
    'Lower B (Arnold)': [
      {'name': 'Cable Lateral Raises', 'primary': true, 'wu': '1~2', 'sets': 3, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
      {'name': 'Hack Squat', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '5~8', 'rest': '3~5', 'muscle': 'رجل كوادز', 'alt1': 'Smith Squat', 'alt2': 'Leg Press', 'note': ''},
      {'name': 'Leg Extension', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل أماميه', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'Hip Adduction', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ضمه', 'alt1': 'Cable Hip Adduction', 'alt2': '', 'note': ''},
      {'name': 'SA Rear Delt Flies', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'كتف خلفي', 'alt1': 'Reverse Pec Dec', 'alt2': '', 'note': ''},
    ],
    'PUSH': [
      {'name': 'Machine Lateral Raises', 'primary': true, 'wu': '1', 'sets': 3, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'Cable Lateral Raises', 'alt2': 'DB Lateral Raises', 'note': ''},
      {'name': 'Incline Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB Incline Press', 'alt2': 'Smith Incline Press', 'note': ''},
      {'name': 'Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~10', 'rest': '3~5', 'muscle': 'صدر مستوي', 'alt1': 'DB Flat Press', 'alt2': 'Smith Flat Press', 'note': ''},
      {'name': 'SA Tricep Pushdown', 'primary': true, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'Double Rope Pushdown', 'alt2': '', 'note': ''},
      {'name': 'Overhead Extension', 'primary': true, 'wu': '1', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'DB Skull Crusher', 'alt2': '', 'note': ''},
      {'name': 'Lat Pulldown Crunches', 'primary': false, 'wu': '1', 'sets': 2, 'reps': '6~10', 'rest': '1~2', 'muscle': 'بطن', 'alt1': 'Cable Crunch', 'alt2': '', 'note': ''},
      {'name': 'Wrist Curls', 'primary': false, 'wu': '1', 'sets': 2, 'reps': '6~10', 'rest': '1~2', 'muscle': 'ساعد خلفي', 'alt1': '', 'alt2': '', 'note': ''},
    ],
    'PULL': [
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': 'Cable Row', 'note': ''},
      {'name': 'SA Lat Row', 'primary': false, 'wu': '1', 'sets': 1, 'reps': '6~10', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable SA Lat Row', 'alt2': 'DB SA Lat Row', 'note': ''},
      {'name': 'Machine Wide Grip Lat Pulldown', 'primary': true, 'wu': '1', 'sets': 1, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable Wide Grip Lat', 'alt2': '', 'note': ''},
      {'name': 'Cable Shrugs', 'primary': false, 'wu': '1', 'sets': 1, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ترابيس', 'alt1': 'Smith Kelso Shrugs', 'alt2': 'T Bar Kelso Shrugs', 'note': ''},
      {'name': 'SA Rear Delt Flies', 'primary': false, 'wu': '1', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'كتف خلفي', 'alt1': 'Reverse Pec Dec', 'alt2': '', 'note': ''},
      {'name': 'DB Curls', 'primary': true, 'wu': '1', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'DB Preacher Curl', 'primary': true, 'wu': '1', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': '', 'alt2': '', 'note': ''},
    ],
    'Lower (PPL)': [
      {'name': 'Hack Squat', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '5~8', 'rest': '3~5', 'muscle': 'رجل كوادز', 'alt1': 'Smith Squat', 'alt2': 'Leg Press', 'note': ''},
      {'name': 'SLDL', 'primary': true, 'wu': '1~3', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'جلوتس', 'alt1': 'RDL', 'alt2': 'Hip Extension', 'note': ''},
      {'name': 'Seated Leg Curl', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل خلفيه', 'alt1': 'Lying Leg Curl', 'alt2': '', 'note': ''},
      {'name': 'Leg Extension', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '8~12', 'rest': '2~3', 'muscle': 'رجل أماميه', 'alt1': '', 'alt2': '', 'note': ''},
      {'name': 'Hip Adduction', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'ضمه', 'alt1': 'Cable Hip Adduction', 'alt2': '', 'note': ''},
      {'name': 'Leg Press Calf Raises', 'primary': false, 'wu': '1~2', 'sets': 3, 'reps': '5~7', 'rest': '1~2', 'muscle': 'سمانة', 'alt1': 'Smith Calf Raises', 'alt2': '', 'note': ''},
      {'name': 'Lat Pulldown Crunches', 'primary': false, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '1~2', 'muscle': 'بطن', 'alt1': 'Cable Crunch', 'alt2': '', 'note': ''},
    ],
    'Upper (PPL)': [
      {'name': 'Machine Wide Grip Lat Pulldown', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'لاتس', 'alt1': 'Cable Wide Grip Lat', 'alt2': '', 'note': ''},
      {'name': 'Chest Press Machine', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '3~5', 'muscle': 'صدر مستوي', 'alt1': 'DB Flat Press', 'alt2': '', 'note': ''},
      {'name': 'T Bar Row', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '5~7', 'rest': '3~5', 'muscle': 'ظهر علوي', 'alt1': 'Incline DB Row', 'alt2': 'Cable Row', 'note': ''},
      {'name': 'Incline Chest Press Machine', 'primary': false, 'wu': '1~2', 'sets': 2, 'reps': '6~10', 'rest': '3~5', 'muscle': 'صدر عالي', 'alt1': 'DB Incline Press', 'alt2': 'Smith Incline Press', 'note': ''},
      {'name': 'Machine Lateral Raises', 'primary': true, 'wu': '1~2', 'sets': 2, 'reps': '6~8', 'rest': '2~3', 'muscle': 'كتف جانبي', 'alt1': 'DB Lateral Raises', 'alt2': '', 'note': ''},
      {'name': 'Face Away Curl', 'primary': true, 'wu': '0', 'sets': 2, 'reps': '6~10', 'rest': '2~3', 'muscle': 'بايسبس', 'alt1': 'DB Preacher Curl', 'alt2': 'DB Curls', 'note': ''},
      {'name': 'SA Tricep Pushdown', 'primary': true, 'wu': '1', 'sets': 2, 'reps': '5~7', 'rest': '2~3', 'muscle': 'ترايسبس', 'alt1': 'Double Rope Pushdown', 'alt2': '', 'note': ''},
    ],
  };

  static Map<String, List<String>> programSessions = {
    'UL': ['Upper A', 'Lower A', 'Upper B', 'Lower B'],
    'AP': ['Anterior A', 'Posterior A', 'Anterior B', 'Posterior B'],
    'FB': ['Full Body #1', 'Full Body #2', 'Full Body #3'],
    'ARNOLD': ['Chest & Back', 'Shoulders & Arms', 'Lower A (Arnold)', 'Upper (Arnold)', 'Lower B (Arnold)'],
    'PPL': ['PUSH', 'PULL', 'Lower (PPL)', 'Upper (PPL)', 'Lower (PPL)'],
    'CUSTOM': [],
  };

  static Map<String, Map<String, dynamic>> programs = {
    'UL': {'id': 'UL', 'name': 'Upper / Lower', 'nameAr': 'علوي / سفلي', 'daysOptions': [4], 'description': 'تقسيم جسم علوي وسفلي', 'descEn': 'Upper/Lower body split'},
    'AP': {'id': 'AP', 'name': 'Anterior / Posterior', 'nameAr': 'أمامي / خلفي', 'daysOptions': [4], 'description': 'نظام أمامي-خلفي', 'descEn': 'Anterior-Posterior split'},
    'FB': {'id': 'FB', 'name': 'Full Body', 'nameAr': 'جسم كامل', 'daysOptions': [3], 'description': 'جسم كامل', 'descEn': 'Full Body training'},
    'ARNOLD': {'id': 'ARNOLD', 'name': 'Arnold', 'nameAr': 'أرنولد', 'daysOptions': [5], 'description': 'برنامج أرنولد الكلاسيكي', 'descEn': 'Classic Arnold program'},
    'PPL': {'id': 'PPL', 'name': 'Push / Pull / Legs', 'nameAr': 'ضغط / شد / أرجل', 'daysOptions': [5], 'description': 'ضغط-شد-أرجل', 'descEn': 'Push-Pull-Legs'},
    'CUSTOM': {'id': 'CUSTOM', 'name': 'Custom Program', 'nameAr': 'برنامج مخصص', 'daysOptions': [3, 4, 5, 6], 'description': 'أضف تمارينك وجلساتك بنفسك', 'descEn': 'Build your own program'},
  };
}
